version: '3.9'
services:
  # backend-1:
  #   build:
  #     context: ./blakjack-backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   container_name: blakjack-backend
  mongodb:
    image: mongo
    container_name: blakjack-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345678
